### ISSUE TITLE
Issue Testing

### ISSUE THREAD

**Issue by mhellmeier** [catenax-ng/product-onboarding#19]
### This issue is only for **testing purposes**, based on a request from @FaGru3n!

The following template is applied by using the "Support: Other topics" section.

----

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have problems with [...]

**Describe the solution you'd like**

Additional context

GitHub user: *your_github_user*

**Comment by FaGru3n** [comment]
@mhellmeier  🚀 Thx for your testing issue worked as expected. 

will leave this issue open for showing purposed into the system-team

**Comment by FaGru3n** [comment]
Hi @mhellmeier  Test worked some templates are moving and for now communication / notifcation - rules are in disscussion.

btw. thanks for the vote ❤️
