### ISSUE TITLE
GitHub: New repository 

### ISSUE THREAD

**Issue by Siegfriedk** [catenax-ng/product-onboarding#25]
Required information:
- Details to your GitHub repository: product-sigis
- Details to GitHub team to grant access: me

hey! hey!

**Comment by FaGru3n** [comment]
@Siegfriedk  we are on it.

**Comment by FaGru3n** [comment]
@https://github.com/eclipse-tractusx/sig-infra/issues/3

**Comment by FaGru3n** [comment]
will close the issue
